//read all users
GET http://localhost:9000/user-api/users
###
//read a user by id
GET http://localhost:9000/user-api/user

###
//create user
POST http://localhost:9000/user-api/users
Content-Type: application/json

{
    "username":"shivaReddy",
    "password":"shivaReddy",
    "email":"shiva123@gmail.com",
    "age":20
}

###
//login user
post http://localhost:9000/user-api/auth
Content-Type: application/json

{
    "email":"shiva123@gmail.com",
    "password":"shivaReddy"
}

###
//update user
PUT http://localhost:9000/user-api/users/69aa973b1a66fd6b338017eb
Content-Type: application/json

{
    "username":"sofaaa",
    "password":"shivareddy@2006",
    "email":"shiava123456@gmail.com",
    "age":20
}

###
DELETE http://localhost:9000/user-api/users/69ac7202d8c858cfa901cd83

// products//
###
GET http://localhost:9000/product-api/products
###
GET http://localhost:9000/product-api/products/69aae8be5d8648a3bd49c1c5
###


POST http://localhost:9000/product-api/products
Content-Type: application/json

{
    "productId":1,
    "productName":"mouse",
    "price":25000,
    "brand":"dell"
}
###
POST http://localhost:9000/product-api/products
Content-Type: application/json

{
    "id":2,
    "name":"macbook",
    "brand":"apple",
    "price":100000
}
###
DELETE http://localhost:9000/product-api/products/69ab06535682b638b4e09910
###
PUT http://localhost:9000/product-api/products/69ab06535682b638b4e09910
Content-Type: application/json

{
     "productId":10,
    "productName":"mouse",
    "price":30000,
    "brand":"dell"
}

###
// add products to user cart(upadte user document)
put http://localhost:9000/user-api/cart/product-id/69b3810a12360b44b850df25



