
### register for Author
POST http://localhost:5000/auth/users
Content-Type: application/json

{
    "firstName":"shiva",
    "lastName":"prasad",
    "email":"author1@mail.com",
    "password":"author-1",
    "role":"AUTHOR",
    "profileImageUrl":""
}


### author login
post http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"author1@mail.com",
    "password":"author-1"
}


### author logout
GET  http://localhost:5000/auth/logout

### create new article
POST http://localhost:5000/author-api/article
Content-Type: application/json

{
    "author":"6a0358d98e5465a55a068834",
    "title":"Article-1 Author 1",
    "category": "programming",
    "content":"codes of front-end"
}


### read own articles
GET http://localhost:5000/author-api/articles


### update article by author (EDIT)
PUT http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "articleId":"69b5889b864838021061d459",
    "title":"Article-1 by Author-1",
    "category":"AI",
    "content":"codes of back-end"
}

### delete /restore article by articleid (soft delete)
PATCH http://localhost:4000/author-api/articles
Content-Type: application/json

{
    "articleId":"69b4d97844da24f5cb60ebd0",
    "isArticleActive":false

}

### change passwoed
PUT http://localhost:4000/auth/password
Content-Type: application/json

{
    "currentPassword":"author1",
    "newPassword":"author-1"
}